import type { CheckResponse } from "./types";

export const MOCK_CHECK: CheckResponse = {
  location: {
    city: "Canton",
    state: "OH",
    lat: 40.79,
    lon: -81.37,
  },
  current: {
    temperature: 72,
    humidity: 45,
    windSpeed: 8,
    precipProbability: 0,
    dewPoint: 52,
    description: "Partly Cloudy",
    hoursUntilRain: 36,
  },
  fetchedAt: "2026-04-18T10:30:00Z",
  cacheExpiresAt: "2026-04-18T11:00:00Z",
  projects: [
    {
      id: "pour-concrete",
      name: "Pour Concrete",
      category: "concrete",
      icon: "🧱",
      status: "green",
      statusLabel: "Good to go",
      reason: "72°F with no rain expected for 36 hours.",
      bestWindow: "Today through tomorrow afternoon",
      nextGoodDay: null,
      details: [
        { label: "Temperature", value: "72°F", requirement: "50–90°F", status: "green" },
        { label: "Rain forecast", value: "None for 36h", requirement: "24h dry required", status: "green" },
        { label: "Humidity", value: "45%", requirement: "Under 80%", status: "green" },
        { label: "Overnight low", value: "55°F", requirement: "Above 40°F", status: "green" },
        { label: "Wind", value: "8 mph", requirement: "Under 25 mph", status: "green" },
      ],
    },
    {
      id: "exterior-paint-latex",
      name: "Exterior Paint (Latex)",
      category: "painting",
      icon: "🎨",
      status: "green",
      statusLabel: "Good to go",
      reason: "Great conditions today — low humidity and a clear dew point margin.",
      bestWindow: "10 AM – 5 PM",
      nextGoodDay: null,
      details: [
        { label: "Temperature", value: "72°F", requirement: "50–85°F", status: "green" },
        { label: "Humidity", value: "45%", requirement: "Under 85%", status: "green" },
        { label: "Dew point margin", value: "20°F below air", requirement: "5°F+ margin", status: "green" },
        { label: "Rain forecast", value: "None for 6h", requirement: "4–6h dry", status: "green" },
      ],
    },
    {
      id: "seal-driveway",
      name: "Seal Concrete/Driveway",
      category: "concrete",
      icon: "🛢️",
      status: "green",
      statusLabel: "Good to go",
      reason: "Warm and dry through Wednesday.",
      bestWindow: "Today through Wednesday",
      nextGoodDay: null,
      details: [
        { label: "Temperature", value: "72°F", requirement: "50–90°F", status: "green" },
        { label: "Rain forecast", value: "None for 36h", requirement: "24h dry", status: "green" },
        { label: "Surface", value: "Dry", requirement: "Must be dry", status: "green" },
      ],
    },
    {
      id: "stain-deck-oil",
      name: "Stain Deck (Oil-Based)",
      category: "painting",
      icon: "🪵",
      status: "yellow",
      statusLabel: "Proceed with caution",
      reason: "Humidity climbing this afternoon — finish by 2 PM.",
      bestWindow: "This morning before noon",
      nextGoodDay: "Thursday",
      details: [
        { label: "Temperature", value: "72°F", requirement: "50–90°F", status: "green" },
        { label: "Humidity", value: "45% → 78%", requirement: "30–70%", status: "yellow" },
        { label: "Rain forecast", value: "None for 36h", requirement: "24–48h dry", status: "green" },
        { label: "Overnight low", value: "55°F", requirement: "No freezing", status: "green" },
      ],
    },
    {
      id: "apply-fertilizer",
      name: "Apply Fertilizer",
      category: "landscaping",
      icon: "🌱",
      status: "yellow",
      statusLabel: "Proceed with caution",
      reason: "No rain for 36 hours — a light watering after may help uptake.",
      bestWindow: "Morning",
      nextGoodDay: "Saturday",
      details: [
        { label: "Temperature", value: "72°F", requirement: "55–85°F", status: "green" },
        { label: "Rain forecast", value: "None for 36h", requirement: "Light rain ideal", status: "yellow" },
        { label: "Wind", value: "8 mph", requirement: "Low is better", status: "green" },
      ],
    },
    {
      id: "spray-paint-outdoor",
      name: "Spray Paint (Outdoor)",
      category: "painting",
      icon: "🧴",
      status: "red",
      statusLabel: "Not today",
      reason: "Gusts reaching 18 mph — need under 15 mph for clean spray.",
      bestWindow: null,
      nextGoodDay: "Wednesday",
      details: [
        { label: "Temperature", value: "72°F", requirement: "50–90°F", status: "green" },
        { label: "Humidity", value: "45%", requirement: "Under 65%", status: "green" },
        { label: "Wind", value: "18 mph gusts", requirement: "Under 15 mph", status: "red" },
        { label: "Rain forecast", value: "None for 36h", requirement: "No rain", status: "green" },
      ],
    },
    {
      id: "apply-herbicide",
      name: "Apply Herbicide",
      category: "landscaping",
      icon: "🌾",
      status: "red",
      statusLabel: "Not today",
      reason: "Wind too high — drift risk to nearby plants.",
      bestWindow: null,
      nextGoodDay: "Wednesday",
      details: [
        { label: "Temperature", value: "72°F", requirement: "60–85°F", status: "green" },
        { label: "Wind", value: "18 mph gusts", requirement: "Under 10 mph", status: "red" },
        { label: "Rain forecast", value: "None for 36h", requirement: "4–6h dry", status: "green" },
      ],
    },
    {
      id: "install-asphalt-shingles",
      name: "Install Asphalt Shingles",
      category: "roofing",
      icon: "🏠",
      status: "green",
      statusLabel: "Good to go",
      reason: "Mild temps and no rain.",
      bestWindow: "All day",
      nextGoodDay: null,
      details: [
        { label: "Temperature", value: "72°F", requirement: "40–85°F", status: "green" },
        { label: "Rain forecast", value: "None for 36h", requirement: "No rain", status: "green" },
        { label: "Wind", value: "8 mph", requirement: "Under 25 mph", status: "green" },
      ],
    },
  ],
};

export const STATUS_ORDER: Record<"green" | "yellow" | "red", number> = {
  green: 0,
  yellow: 1,
  red: 2,
};
